const $=s=>document.querySelector(s);
const fileInput=$('#files'),queueEl=$('#queue'),template=$('#jobTemplate'),statsEl=$('#stats'),statusEl=$('#status'),qualityHint=$('#qualityHint'),customMB=$('#customMB');
const audioEl=$('#audio'),strictEl=$('#strict'),skipSmallEl=$('#skipSmall'),awakeEl=$('#awake'),safeRetryEl=$('#safeRetry');
const compressAllBtn=$('#compressAll'),cancelBtn=$('#cancel'),downloadAllBtn=$('#downloadAll'),retryFailedBtn=$('#retryFailed'),clearFinishedBtn=$('#clearFinished'),removeDupesBtn=$('#removeDupes'),smallFirstBtn=$('#smallFirst'),clearAllBtn=$('#clearAll');
const editor=$('#editor'),preview=$('#preview'),editorName=$('#editorName'),startRange=$('#startRange'),endRange=$('#endRange'),startText=$('#startText'),endText=$('#endText'),cutsEl=$('#cuts'),timeline=$('#timeline');
let jobs=[],targetMB=20,mode='quality',running=false,cancelRequested=false,activeJob=null,currentRecorder=null,wakeLock=null,smallFirst=false;
const SETTINGS_KEY='clipcompress-v9-settings',SAFE_MARGIN=.90;
init();

async function init(){await loadSettings();renderSettings();bindEvents();renderQueue();updateQualityHint();}
function bindEvents(){
 document.querySelectorAll('#targets button').forEach(btn=>btn.addEventListener('click',()=>{targetMB=Number(btn.dataset.mb);customMB.value='';document.querySelectorAll('#targets button').forEach(x=>x.classList.toggle('active',x===btn));invalidateFinished();saveSettings();updateQualityHint();renderQueue();}));
 customMB.addEventListener('input',()=>{const n=Number(customMB.value);if(Number.isFinite(n)&&n>=1){targetMB=n;document.querySelectorAll('#targets button').forEach(x=>x.classList.remove('active'));invalidateFinished();saveSettings();updateQualityHint();renderQueue();}});
 document.querySelectorAll('.mode').forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===btn));invalidateFinished();saveSettings();renderQueue();}));
 for(const el of [audioEl,strictEl,skipSmallEl,awakeEl,safeRetryEl]) el.addEventListener('change',()=>{invalidateFinished();saveSettings();renderQueue();updateQualityHint();});
 fileInput.addEventListener('change',importFiles);compressAllBtn.addEventListener('click',runBatch);cancelBtn.addEventListener('click',cancelCurrent);clearAllBtn.addEventListener('click',clearAll);smallFirstBtn.addEventListener('click',sortSmallest);retryFailedBtn.addEventListener('click',retryFailed);clearFinishedBtn.addEventListener('click',clearFinished);removeDupesBtn.addEventListener('click',removeDuplicates);downloadAllBtn.addEventListener('click',downloadAll);
 $('#closeEditor').addEventListener('click',closeEditor);$('#doneEditor').addEventListener('click',closeEditor);$('#clearCuts').addEventListener('click',()=>{if(!activeJob)return;activeJob.cuts=[];invalidateJob(activeJob);renderCuts();});
 $('#useStart').addEventListener('click',()=>{if(!activeJob)return;startRange.value=Math.max(0,Math.min(preview.currentTime,Number(endRange.value)-.05));syncCutLabels();});
 $('#useEnd').addEventListener('click',()=>{if(!activeJob)return;endRange.value=Math.min(activeJob.duration,Math.max(preview.currentTime,Number(startRange.value)+.05));syncCutLabels();});
 startRange.addEventListener('input',()=>{if(Number(startRange.value)>=Number(endRange.value))startRange.value=Math.max(0,Number(endRange.value)-.05);preview.currentTime=Number(startRange.value);syncCutLabels();});
 endRange.addEventListener('input',()=>{if(Number(endRange.value)<=Number(startRange.value))endRange.value=Math.min(activeJob?.duration||1,Number(startRange.value)+.05);preview.currentTime=Number(endRange.value);syncCutLabels();});
 $('#addCut').addEventListener('click',addCut);document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&running)await requestWakeLock();});
}
async function loadSettings(){try{const data=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'),s=data||{};if(Number(s.targetMB)>=1)targetMB=Number(s.targetMB);if(['quality','fast','light'].includes(s.mode))mode=s.mode;if(typeof s.audio==='boolean')audioEl.checked=s.audio;if(typeof s.strict==='boolean')strictEl.checked=s.strict;if(typeof s.skipSmall==='boolean')skipSmallEl.checked=s.skipSmall;if(typeof s.awake==='boolean')awakeEl.checked=s.awake;if(typeof s.safeRetry==='boolean')safeRetryEl.checked=s.safeRetry;}catch{}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({targetMB,mode,audio:audioEl.checked,strict:strictEl.checked,skipSmall:skipSmallEl.checked,awake:awakeEl.checked,safeRetry:safeRetryEl.checked}));}catch{}}
function renderSettings(){document.querySelectorAll('#targets button').forEach(x=>x.classList.toggle('active',Number(x.dataset.mb)===targetMB));if(![8,20,25,50,100].includes(targetMB))customMB.value=String(targetMB);document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));}

async function importFiles(){const files=[...fileInput.files];fileInput.value='';const existing=new Set(jobs.map(j=>fileKey(j.file)));for(const file of files){try{const meta=await readMetadata(file);jobs.push(makeJob(file,meta.duration,existing.has(fileKey(file))));}catch(error){const j=makeJob(file,0,existing.has(fileKey(file)));j.state='error';j.error="Your browser could not read this video's metadata.";j.errorDetails=String(error?.stack||error);jobs.push(j);}existing.add(fileKey(file));}if(smallFirst)jobs.sort((a,b)=>a.file.size-b.file.size);refreshDuplicateFlags();renderQueue();updateQualityHint();}
function makeJob(file,duration,duplicate=false){return{id:crypto.randomUUID(),file,duration,duplicate,cuts:[],state:'ready',progress:0,output:null,outputSize:0,outputName:'',error:'',errorDetails:'',note:'',retryStage:0,attempt:0};}

async function runBatch(){if(running||!jobs.length)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){alert('This browser cannot record compressed video. Try the latest Chrome or Safari.');return;}running=true;cancelRequested=false;await requestWakeLock();renderQueue();try{const list=jobs.filter(j=>j.state!=='done');if(smallFirst)list.sort((a,b)=>a.file.size-b.file.size);for(const job of list){if(cancelRequested)break;if(job.state==='error'){job.state='ready';job.error='';job.errorDetails='';}await processJob(job);}}finally{running=false;cancelRequested=false;currentRecorder=null;await releaseWakeLock();statusEl.textContent='Ready • browser video encoder';renderQueue();}}

async function processJob(job){
 if(skipSmallEl.checked&&!job.cuts.length&&job.file.size<=targetBytes()){disposeOutput(job);job.output={blob:job.file,file:job.file,url:URL.createObjectURL(job.file)};job.outputSize=job.file.size;job.outputName=job.file.name;job.state='done';job.progress=1;job.note='Already under target — original kept.';renderQueue();return;}
 job.attempt=1;job.retryStage=0;const primary=profileForMode(mode);const firstRate=calcBitrate(job,primary,SAFE_MARGIN);
 try{await nativeEncode(job,primary,firstRate);if(strictEl.checked&&job.outputSize>targetBytes()*1.02&&!cancelRequested){const ratio=targetBytes()/job.outputSize,secondRate=Math.max(180000,Math.floor(firstRate*ratio*.91));job.attempt=2;job.note='Retrying 720p for a safer file size…';renderQueue();try{await nativeEncode(job,primary,secondRate);}catch(retryError){
 job.errorDetails='A strict-size retry failed: '+errorDetails(retryError);
 throw retryError;
 }}return;}
 catch(error){cleanupFailedAttempt(job);if(cancelRequested||/cancelled/i.test(String(error?.message||error))){job.state='cancelled';job.error='';job.errorDetails='';renderQueue();return;}const firstDetails=errorDetails(error);
  if(safeRetryEl.checked){try{job.retryStage=1;job.attempt+=1;job.note='Primary encode failed — retrying 720p with safer settings…';renderQueue();const safe720={height:720,fps:20,label:'720p Safe Retry',mimePreference:'vp8'};await sleep(250);await nativeEncode(job,safe720,calcBitrate(job,safe720,.84));return;}catch(retryError){cleanupFailedAttempt(job);try{job.retryStage=2;job.attempt+=1;job.note='720p retry failed — final compatibility retry at 540p…';renderQueue();const compat={height:540,fps:20,label:'540p Compatibility',mimePreference:'vp8'};await sleep(250);await nativeEncode(job,compat,calcBitrate(job,compat,.82));return;}catch(finalError){cleanupFailedAttempt(job);job.state='error';job.error=friendlyError(finalError);job.errorDetails=`Primary attempt:\n${firstDetails}\n\nFinal retry:\n${errorDetails(finalError)}`;renderQueue();return;}}}
  job.state='error';job.error=friendlyError(error);job.errorDetails=firstDetails;renderQueue();}
}

async function nativeEncode(job,profile,totalBitrate){
 job.state='processing';job.progress=0;job.error='';job.errorDetails='';disposeOutput(job);renderQueue();
 const video=document.createElement('video'),canvas=document.createElement('canvas');video.className='workbench';canvas.className='workbench';video.preload='auto';video.playsInline=true;document.body.append(video,canvas);
 const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true}),sourceURL=URL.createObjectURL(job.file);video.src=sourceURL;
 let recorder=null,audioContext=null,audioSource=null,audioDest=null,outStream=null,chunks=[],stoppedDrawing=false,stopPromise=null;
 try{
  await waitEvent(video,'loadedmetadata',15000);await waitEvent(video,'canplay',15000).catch(()=>{});if(!video.videoWidth||!video.videoHeight)throw new Error('Video decoder did not expose a valid frame size.');
  const dims=fitDimensions(video.videoWidth,video.videoHeight,profile.height);canvas.width=dims.width;canvas.height=dims.height;const canvasStream=canvas.captureStream(profile.fps),tracks=[...canvasStream.getVideoTracks()];
  let audioIncluded=false;if(audioEl.checked){try{audioContext=new AudioContext({latencyHint:'playback'});audioSource=audioContext.createMediaElementSource(video);audioDest=audioContext.createMediaStreamDestination();audioSource.connect(audioDest);await audioContext.resume();const a=audioDest.stream.getAudioTracks()[0];if(a){tracks.push(a);audioIncluded=true;}}catch(error){console.warn('Audio capture unavailable, continuing video-only',error);}}
  outStream=new MediaStream(tracks);const mime=chooseMime(audioIncluded,profile.mimePreference);if(!mime)throw new Error('Your browser did not provide a supported MediaRecorder video format.');
  const audioRate=audioIncluded?Math.min(96000,Math.max(40000,Math.floor(totalBitrate*.07))):0,videoRate=Math.max(140000,totalBitrate-audioRate),options={mimeType:mime,videoBitsPerSecond:videoRate};if(audioIncluded)options.audioBitsPerSecond=audioRate;
  recorder=new MediaRecorder(outStream,options);currentRecorder=recorder;recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};stopPromise=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||new Error('Browser recorder failed.'));});
  const ranges=keepRanges(job.duration,job.cuts);if(!ranges.length)throw new Error('All of the video is inside removed cut sections.');await seek(video,ranges[0].start);drawFrame(ctx,video,canvas);drawLoop(video,ctx,canvas,()=>stoppedDrawing);
  recorder.start(1000);const started=performance.now();let completed=0;const finalDuration=ranges.reduce((s,r)=>s+(r.end-r.start),0);
  for(let i=0;i<ranges.length;i++){const r=ranges[i];if(cancelRequested)throw new Error('cancelled');if(i>0){if(recorder.state==='recording')recorder.pause();video.pause();await seek(video,r.start);drawFrame(ctx,video,canvas);if(recorder.state==='paused')recorder.resume();}await video.play();while(video.currentTime<r.end-.03 && !video.ended){if(cancelRequested)throw new Error('cancelled');if(video.error)throw new Error(`Browser video decoder error ${video.error.code}.`);if(video.paused && !video.ended) throw new Error('Playback paused unexpectedly. Keep the page visible during conversion.');const within=Math.max(0,Math.min(r.end-r.start,video.currentTime-r.start));job.progress=Math.min(.995,(completed+within)/finalDuration);updateProgress(job,started);await sleep(80);}video.pause();completed+=r.end-r.start;job.progress=Math.min(.995,completed/finalDuration);}
  if(recorder.state!=='inactive')recorder.stop();await stopPromise;stoppedDrawing=true;if(cancelRequested)throw new Error('cancelled');const blob=new Blob(chunks,{type:recorder.mimeType||mime});if(!blob.size)throw new Error('The browser returned an empty encoded video.');
  const ext=blob.type.includes('mp4')?'mp4':'webm',fileName=`${stripExt(job.file.name)}-compressed.${ext}`,outFile=new File([blob],fileName,{type:blob.type}),url=URL.createObjectURL(blob);job.output={blob,file:outFile,url};job.outputSize=blob.size;job.outputName=fileName;job.state='done';job.progress=1;job.note=`${profile.label} finished${audioEl.checked&&!audioIncluded?' • audio unavailable':''}${blob.size>targetBytes()*1.02?' • over target':''}`;
 }finally{
  stoppedDrawing=true;try{video.pause();}catch{}try{if(recorder&&recorder.state!=='inactive'){recorder.stop();await Promise.race([stopPromise||Promise.resolve(),sleep(800)]);}}catch{}if(outStream){for(const t of outStream.getTracks()){try{t.stop();}catch{}}}try{audioSource?.disconnect();}catch{}try{audioDest?.disconnect?.();}catch{}try{if(audioContext&&audioContext.state!=='closed')await audioContext.close();}catch{}
  chunks=[];currentRecorder=null;URL.revokeObjectURL(sourceURL);video.removeAttribute('src');try{video.load();}catch{}video.remove();canvas.width=1;canvas.height=1;canvas.remove();await sleep(180);
 }
}

function chooseMime(withAudio,preference='best'){const groups={best:withAudio?['video/mp4;codecs="avc1.42E01E,mp4a.40.2"','video/mp4;codecs="avc1.42E01E"','video/webm;codecs="vp9,opus"','video/webm;codecs="vp8,opus"','video/webm']:['video/mp4;codecs="avc1.42E01E"','video/webm;codecs="vp9"','video/webm;codecs="vp8"','video/webm'],vp8:withAudio?['video/webm;codecs="vp8,opus"','video/webm','video/mp4;codecs="avc1.42E01E,mp4a.40.2"','video/mp4']:['video/webm;codecs="vp8"','video/webm','video/mp4;codecs="avc1.42E01E"','video/mp4']};for(const type of groups[preference]||groups.best){try{if(MediaRecorder.isTypeSupported(type))return type;}catch{}}return '';}
function profileForMode(m){if(m==='fast')return{height:720,fps:24,label:'720p Fast',mimePreference:'best'};if(m==='light')return{height:540,fps:24,label:'540p Light',mimePreference:'best'};return{height:720,fps:30,label:'720p Quality',mimePreference:'best'};}
function calcBitrate(job,profile,safety=SAFE_MARGIN){const duration=Math.max(.1,job.duration-totalCutDuration(job.cuts,job.duration)),bytes=targetBytesRaw()*safety;return Math.max(180000,Math.floor(bytes*8/duration));}
function targetBytesRaw(){return Math.max(1000000,targetMB*1000000);}function targetBytes(){return Math.floor(targetBytesRaw()*SAFE_MARGIN);}
function fitDimensions(sw,sh,targetHeight){const portrait=sh>sw,maxW=portrait?targetHeight:Math.round(targetHeight*16/9),maxH=portrait?Math.round(targetHeight*16/9):targetHeight,scale=Math.min(1,maxW/sw,maxH/sh);let width=Math.max(2,Math.round(sw*scale)),height=Math.max(2,Math.round(sh*scale));if(width%2)width--;if(height%2)height--;return{width,height};}
function drawFrame(ctx,video,canvas){if(video.readyState>=2)ctx.drawImage(video,0,0,canvas.width,canvas.height);}function drawLoop(video,ctx,canvas,stopped){const cb=()=>{if(stopped())return;drawFrame(ctx,video,canvas);if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(cb);else requestAnimationFrame(cb);};cb();}
function updateProgress(job,started){const row=document.querySelector(`.job[data-id="${job.id}"]`);if(!row)return;const bar=row.querySelector('.progress');bar.hidden=false;bar.querySelector('div').style.width=`${Math.max(2,job.progress*100)}%`;const elapsed=(performance.now()-started)/1000,remain=job.progress>.03?Math.max(0,elapsed/job.progress-elapsed):0;row.querySelector('.jobStatus').textContent=`Converting… ${Math.round(job.progress*100)}%${remain?` • ~${humanTime(remain)} left`:''}`;}
function cleanupFailedAttempt(job){disposeOutput(job);job.progress=0;}function disposeOutput(job){if(job.output?.url){try{URL.revokeObjectURL(job.output.url);}catch{}}job.output=null;job.outputSize=0;job.outputName='';}
function invalidateFinished(){if(running)return;for(const j of jobs){if(j.state==='done'){disposeOutput(j);j.state='ready';j.note='';j.progress=0;}}}function invalidateJob(j){disposeOutput(j);j.state='ready';j.note='';j.error='';j.errorDetails='';j.progress=0;j.retryStage=0;}
function friendlyError(error){const m=String(error?.message||error);if(/decoder|media decode|video decoder/i.test(m))return 'Chrome could not decode this source video. Tap Details.';if(/memory|allocation|out of memory/i.test(m))return 'Chrome hit a memory limit. Resources were released; retry this video by itself.';if(/empty encoded video/i.test(m))return 'Chrome produced an empty output. Tap Details.';if(/MediaRecorder|supported.*format/i.test(m))return 'Chrome could not start its video encoder. Tap Details.';return m.length>150?'Conversion failed. Tap Details.':m;}function errorDetails(error){return String(error?.stack||error?.message||error);}
function cancelCurrent(){if(!running)return;cancelRequested=true;statusEl.textContent='Cancelling current video…';try{if(currentRecorder&&currentRecorder.state!=='inactive')currentRecorder.stop();}catch{}}
function clearAll(){if(running)return;for(const j of jobs)disposeOutput(j);jobs=[];renderQueue();updateQualityHint();}function sortSmallest(){if(running)return;smallFirst=true;jobs.sort((a,b)=>a.file.size-b.file.size);smallFirstBtn.textContent='Smallest first ✓';renderQueue();}
async function retryFailed(){if(running)return;for(const j of jobs){if(j.state==='error'||j.state==='cancelled'){j.state='ready';j.error='';j.errorDetails='';j.retryStage=0;j.progress=0;}}renderQueue();await runBatch();}
function clearFinished(){if(running)return;const done=jobs.filter(j=>j.state==='done');for(const j of done)disposeOutput(j);jobs=jobs.filter(j=>j.state!=='done');renderQueue();}
function removeDuplicates(){if(running)return;const seen=new Set(),kept=[];for(const j of jobs){const k=fileKey(j.file);if(seen.has(k))disposeOutput(j);else{seen.add(k);kept.push(j);}}jobs=kept;refreshDuplicateFlags();renderQueue();}
async function downloadAll(){for(const job of jobs.filter(j=>j.state==='done'&&j.output?.url)){await downloadJob(job,false);await sleep(120);}}
async function downloadJob(job,saveAs=true){
 if(!job.output?.url)return;
 const f=job.output.file;
 if(navigator.share && navigator.canShare?.({files:[f]})){
  try{await navigator.share({files:[f],title:f.name});return;}catch(e){if(e?.name==='AbortError')return;}
 }
 const a=document.createElement('a');a.href=job.output.url;a.download=job.outputName||'compressed-video.webm';document.body.append(a);a.click();a.remove();
}
function sanitizeName(name){return name.replace(/[<>:"/\\|?*\x00-\x1F]/g,'_');}function refreshDuplicateFlags(){const seen=new Set();for(const j of jobs){const k=fileKey(j.file);j.duplicate=seen.has(k);seen.add(k);}}function fileKey(f){return`${f.name}|${f.size}|${f.lastModified}`;}

function renderQueue(){refreshDuplicateFlags();const done=jobs.filter(j=>j.state==='done').length,failed=jobs.filter(j=>j.state==='error').length,totalBytes=jobs.reduce((s,j)=>s+j.file.size,0);statsEl.textContent=jobs.length?`${jobs.length} video${jobs.length===1?'':'s'} • ${formatBytes(totalBytes)} • ${done} finished${failed?` • ${failed} failed`:''}`:'No videos yet.';retryFailedBtn.hidden=!failed&&!jobs.some(j=>j.state==='cancelled');clearFinishedBtn.hidden=!done;downloadAllBtn.hidden=!done;removeDupesBtn.hidden=!jobs.some(j=>j.duplicate);queueEl.innerHTML='';if(!jobs.length){queueEl.className='queue empty';queueEl.innerHTML='<div class="emptyState"><div>🎬</div><b>No videos yet</b><span>Add videos above.</span></div>';compressAllBtn.disabled=true;cancelBtn.hidden=true;return;}queueEl.className='queue';compressAllBtn.disabled=running;compressAllBtn.textContent=running?'Compressing queue…':'Compress all';cancelBtn.hidden=!running;
 for(const job of jobs){const node=template.content.cloneNode(true),article=node.querySelector('.job');article.dataset.id=job.id;node.querySelector('.name').textContent=job.file.name;node.querySelector('.meta').textContent=`${formatBytes(job.file.size)} • ${formatTime(job.duration)} • target ${targetMB} MB`;node.querySelector('.cutMeta').textContent=job.cuts.length?`${job.cuts.length} cut${job.cuts.length===1?'':'s'} • removes ${formatTime(totalCutDuration(job.cuts,job.duration))}`:'';const badges=[],prof=profileForMode(mode);badges.push(`<span class="badge good">${prof.label}</span>`);if(job.retryStage===1)badges.push('<span class="badge warn">Safe retry</span>');if(job.retryStage===2)badges.push('<span class="badge warn">Compatibility retry</span>');if(job.duplicate)badges.push('<span class="badge warn">Possible duplicate</span>');if(!audioEl.checked)badges.push('<span class="badge">Muted</span>');if(job.cuts.length)badges.push(`<span class="badge">${job.cuts.length} cut${job.cuts.length===1?'':'s'}</span>`);node.querySelector('.badges').innerHTML=badges.join('');
  const status=node.querySelector('.jobStatus'),progress=node.querySelector('.progress'),result=node.querySelector('.result'),download=node.querySelector('.download'),details=node.querySelector('.details');if(job.state==='processing'){progress.hidden=false;progress.querySelector('div').style.width=`${Math.max(2,job.progress*100)}%`;status.textContent=`Converting… ${Math.round(job.progress*100)}%`;}else if(job.state==='done'){status.textContent=job.note||'Finished';result.hidden=false;result.textContent=`${formatBytes(job.file.size)} → ${formatBytes(job.outputSize)}`;download.hidden=false;}else if(job.state==='error'){status.classList.add('error');status.textContent=`Conversion failed: ${job.error}`;details.hidden=!job.errorDetails;}else if(job.state==='cancelled'){status.classList.add('cancelled');status.textContent='Cancelled • original video is unchanged';}else{const d=Math.max(0,job.duration-totalCutDuration(job.cuts,job.duration));status.textContent=skipSmallEl.checked&&!job.cuts.length&&job.file.size<=targetBytes()?'Ready • already under target':`Ready • estimated conversion ~${humanTime(d)}`;}
  node.querySelector('.remove').disabled=running;node.querySelector('.remove').addEventListener('click',()=>{if(running)return;disposeOutput(job);jobs=jobs.filter(j=>j.id!==job.id);renderQueue();updateQualityHint();});node.querySelector('.edit').disabled=running||!job.duration;node.querySelector('.edit').addEventListener('click',()=>openEditor(job));node.querySelector('.one').disabled=running||job.state==='processing';node.querySelector('.one').addEventListener('click',async()=>{if(running)return;running=true;cancelRequested=false;await requestWakeLock();renderQueue();try{await processJob(job);}finally{running=false;cancelRequested=false;await releaseWakeLock();renderQueue();}});details.addEventListener('click',()=>alert(job.errorDetails||job.error||'No additional details.'));download.addEventListener('click',()=>downloadJob(job,true));queueEl.appendChild(node);}}

function updateQualityHint(){if(!jobs.length){qualityHint.className='hint';qualityHint.textContent='';return;}const longest=jobs.reduce((a,b)=>a.duration>b.duration?a:b),duration=Math.max(.1,longest.duration-totalCutDuration(longest.cuts,longest.duration)),kbps=Math.round(targetBytes()*8/duration/1000);qualityHint.className='hint show';if(kbps<450){qualityHint.classList.add('warn');qualityHint.textContent=`${targetMB} MB over ${formatTime(duration)} is only about ${kbps} kbps total. 720p will be soft; raising the target is may not give sharp 720p at this length.`;}else if(kbps>=900){qualityHint.classList.add('good');qualityHint.textContent=`About ${kbps} kbps available for the longest clip. 720p screen detail should hold up well.`;}else qualityHint.textContent=`About ${kbps} kbps available for the longest clip. 720p should be usable, especially for screen recordings.`;}
function openEditor(job){activeJob=job;editorName.textContent=job.file.name;preview.src=URL.createObjectURL(job.file);startRange.max=job.duration;endRange.max=job.duration;startRange.value=0;endRange.value=Math.min(job.duration,Math.max(1,job.duration*.1));syncCutLabels();renderCuts();editor.showModal();}
function closeEditor(){preview.pause();if(preview.src.startsWith('blob:'))URL.revokeObjectURL(preview.src);preview.removeAttribute('src');preview.load();activeJob=null;editor.close();renderQueue();updateQualityHint();}
function addCut(){if(!activeJob)return;const start=Number(startRange.value),end=Number(endRange.value);if(end<=start+.04)return;activeJob.cuts.push({id:crypto.randomUUID(),start,end});activeJob.cuts=mergeCuts(activeJob.cuts,activeJob.duration);invalidateJob(activeJob);renderCuts();}
function syncCutLabels(){startText.textContent=formatTime(Number(startRange.value));endText.textContent=formatTime(Number(endRange.value));}
function renderCuts(){if(!activeJob)return;cutsEl.innerHTML='';timeline.innerHTML='';if(!activeJob.cuts.length)cutsEl.innerHTML='<div class="jobStatus">No cuts yet.</div>';for(const cut of activeJob.cuts){const block=document.createElement('div');block.className='cutBlock';block.style.left=`${cut.start/activeJob.duration*100}%`;block.style.width=`${(cut.end-cut.start)/activeJob.duration*100}%`;timeline.appendChild(block);const row=document.createElement('div');row.className='cutRow';row.innerHTML=`<span>${formatTime(cut.start)} → ${formatTime(cut.end)}</span><span>-${formatTime(cut.end-cut.start)}</span><button>×</button>`;row.querySelector('button').addEventListener('click',()=>{activeJob.cuts=activeJob.cuts.filter(x=>x.id!==cut.id);invalidateJob(activeJob);renderCuts();});cutsEl.appendChild(row);}}
function keepRanges(duration,cuts){const merged=mergeCuts(cuts,duration),out=[];let cursor=0;for(const c of merged){if(c.start>cursor)out.push({start:cursor,end:c.start});cursor=Math.max(cursor,c.end);}if(cursor<duration)out.push({start:cursor,end:duration});return out.filter(r=>r.end-r.start>.02);}
function mergeCuts(cuts,duration){const list=(cuts||[]).map(c=>({id:c.id||crypto.randomUUID(),start:Math.max(0,Math.min(duration,Math.min(c.start,c.end))),end:Math.max(0,Math.min(duration,Math.max(c.start,c.end)))})).filter(c=>c.end-c.start>.01).sort((a,b)=>a.start-b.start),out=[];for(const c of list){const last=out[out.length-1];if(last&&c.start<=last.end)last.end=Math.max(last.end,c.end);else out.push({...c});}return out;}
function totalCutDuration(cuts,duration){return mergeCuts(cuts,duration).reduce((s,c)=>s+(c.end-c.start),0);}
function readMetadata(file){return new Promise((resolve,reject)=>{const v=document.createElement('video'),url=URL.createObjectURL(file);v.preload='metadata';v.onloadedmetadata=()=>{const duration=Number.isFinite(v.duration)?v.duration:0;URL.revokeObjectURL(url);v.removeAttribute('src');resolve({duration});};v.onerror=()=>{URL.revokeObjectURL(url);v.removeAttribute('src');v.load();reject(new Error(`Metadata load failed for ${file.name}`));};v.src=url;});}
async function seek(video,time){if(Math.abs(video.currentTime-time)<.02)return;const p=waitEvent(video,'seeked',10000);video.currentTime=Math.max(0,time);await p;}
function waitEvent(el,name,timeout=10000){return new Promise((resolve,reject)=>{let timer;const done=()=>{clearTimeout(timer);el.removeEventListener(name,done);resolve();};el.addEventListener(name,done,{once:true});timer=setTimeout(()=>{el.removeEventListener(name,done);reject(new Error(`${name} timed out`));},timeout);});}
async function requestWakeLock(){if(!awakeEl.checked||!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen');}catch{}}async function releaseWakeLock(){try{await wakeLock?.release();}catch{}wakeLock=null;}
function stripExt(name){return name.replace(/\.[^.]+$/,'')||'video';}function sleep(ms){return new Promise(r=>setTimeout(r,ms));}function formatBytes(bytes){const units=['B','KB','MB','GB'];let n=bytes,i=0;while(n>=1000&&i<units.length-1){n/=1000;i++;}return`${n.toFixed(i===0?0:n>=100?0:1)} ${units[i]}`;}function formatTime(seconds){const s=Math.max(0,Number(seconds)||0),m=Math.floor(s/60),sec=s-m*60;return`${m}:${sec.toFixed(2).padStart(5,'0')}`;}function humanTime(seconds){const s=Math.max(0,Math.round(seconds));if(s<60)return`${s}s`;const m=Math.floor(s/60);if(m<60)return`${m}m ${s%60}s`;return`${Math.floor(m/60)}h ${m%60}m`;}

if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
